require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.3

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - 'spec/**/*_spec.rb'
    - 'spec/shared_examples/*.rb'
    - 'zenaton.gemspec'

Metrics/ClassLength:
  Enabled: true
  Exclude:
    - 'lib/zenaton/client.rb'
    - 'lib/zenaton/services/serializer.rb'

Metrics/ModuleLength:
  Enabled: true
  Exclude:
    - 'lib/zenaton/traits/with_timestamp.rb'

Style/NumericLiterals:
  Enabled: false
