require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.3

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - 'spec/**/*_spec.rb'

Metrics/ClassLength:
  Enabled: true
  Exclude:
    - 'lib/zenaton/client.rb'
