require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.3

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - 'spec/**/*_spec.rb'
    - 'spec/shared_examples/*.rb'
    - 'zenaton-ruby.gemspec'

Metrics/ClassLength:
  Enabled: true
  Exclude:
    - 'lib/zenaton/client.rb'

Style/NumericLiterals:
  Enabled: false
